name: Deploy Project
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ vars.BUN_VERSION }}
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install dependencies
        run: bun i
      - name: Build project
        run: bun run build
      - name: List files
        run: ls -la dist
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
      - name: Force failure
        run: exit 1

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."

  notify-success:
    needs:
      - build
      - deploy
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421700405376585879/e1Wc5sJiPEzTAEKaU9aFalGCgvMaBX_vV5-l7dmODD47Mex1IBvHX5OJtZIFnr16DzR7
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project ${{ github.event.repository.full_name }} has been deployed. by ${{ github.actor }} status: success.'
      - name: Final step
        run: echo "Deployment complete!"

  notify-failure:
    needs:
      - build
      - deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421700405376585879/e1Wc5sJiPEzTAEKaU9aFalGCgvMaBX_vV5-l7dmODD47Mex1IBvHX5OJtZIFnr16DzR7
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project ${{ github.event.repository.full_name }} has been deployed. by ${{ github.actor }} status: failure. This is why it failed: ${{ needs.build.result }}'
      - name: Final step
        run: echo "Deployment complete!"
