name: Deploy Project
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.USERNAME }}/react-demo1:latest

  notify-success:
    needs:
      - build
      - deploy
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project ${{ github.event.repository.full_name }} has been deployed. by ${{ github.actor }} status: success.'
      - name: Final step
        run: echo "Deployment complete!"

  notify-failure:
    needs:
      - build
      - deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project ${{ github.event.repository.full_name }} has been deployed. by ${{ github.actor }} status: failure. This is why it failed: ${{ needs.build }}'
      - name: Final step
        run: echo "Deployment complete!"
