name: Deploy Project
on:
  push:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Set up Bun
        uses: oven-sh/bun@v2
        with:
          bun-version: 1.2.22
      - name: Install dependencies
        run: bun i
      - name: Run linter
        run: bun run lint
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Set up Bun
        uses: oven-sh/bun@v2
        with:
          bun-version: 1.2.22
      - name: Install dependencies
        run: bun i
      - name: Run build
        run: bun run build
      - name: List dist/
        run: ls -la dist/
      - name: Deploy
        run: echo "Deploying..."
